### ISSUE TITLE
符号导致错误

### ISSUE THREAD

**Issue by mabangde** [inspiringz/fofa#1]
输入带"-" 符号的域名会解析错误
如 bai-du.com  
windows cmd环境

**Comment by inspiringz** [comment]
Hi, Windows 环境下通过 CMD 命令行传入 query(-q) 参数时可以尝试通过双引号包裹, 并使用斜杠对 query 规则中的 `"` 进行转义。

```
Unix: -q 'domain="baidu-inc.com"
Windows: -q "domain=\"baidu-inc.com\""
```

![image](https://user-images.githubusercontent.com/47313597/144707439-0d18722e-59bd-4cd7-892f-9d2d8be72d5d.png)


![image](https://user-images.githubusercontent.com/47313597/144707369-0c9759be-b655-43eb-aa40-d1a8a32aa3f2.png)
