### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by charis3306** [inspiringz/fofa#2]
panic: runtime error: invalid memory address or nil pointer dereference
![image](https://user-images.githubusercontent.com/84823804/191688554-1565dc8c-bc57-432c-b2e0-ec7fb611a3e3.png)

**Comment by inspiringz** [comment]
release 的貌似有点问题, 可以下载代码自行编译运行~

**Comment by charis3306** [comment]
问题解决了，排查是自己代理问题。感谢师傅回复。没有用release 自己编译的。
